### PR TITLE
Upgrade to scalajs 1 series.

### PR DESCRIPTION
**Pull request by vic**
Still waiting for boopickle to be released for scalajs 1.0.0
WIP: https://github.com/suzaku-io/boopickle/pull/118

Closes #47

### CODE REVIEW

**Comment by vic** [comment]
boopickle has been updated sjs1, we are just waiting for artifacts to be published.

https://github.com/suzaku-io/boopickle/issues/117

**Comment by ioleo** [comment]
@vic thanks for your work, I see boopickle is already published for 1.0, but my understanding is, there is a problem and you're waiting for a fix to be published, is that correct?

**Comment by vic** [comment]
@ioleo, Yes, I tried using `1.3.2` after just like 30mins after it was published :D, but the artifact had some `sjsir` incompatibilities. @ochrons commented that perhaps `1.3.3` would be published, but haven't looked at it.

So, yes, we are waiting for a working version.

**Comment by cornerman** [comment]
Thanks for the update - let's keep on waiting then :)

**Comment by vic** [comment]
Self reminder to try again when the following issue gets closed.

https://github.com/suzaku-io/boopickle/issues/127

**Comment by cornerman** [comment]
@vic Woohoo! Bookpickle is released now :tada:

**Comment by vic** [comment]
@cornerman, rebased now, all tests are green. 

Feel free to publish a new release and I'll also update https://github.com/cornerman/sloth/pull/55 afterwards.

**Comment by cornerman** [comment]
@vic Finally done - made a release of version `0.3.0`!

**Comment by vic** [comment]
@cornerman Awesome!, thank you so much :)

**Pull request merged**
